title: History in Translation
name_first: Mateusz
name_last: Fafinski
position: PhD
tagline: "Mateusz Fafinski"
description: "The personal blog of Mateusz Fafinski, PhD, historian and digital humanist"
